import { Video, youtubeSearch } from "./videoTypes";

export const absVideos: Video[] = [
  {
    id: "kinniku-abs",
    title: "腹筋を割る正しいトレーニング",
    youtuber: "なかやまきんに君",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("なかやまきんに君 腹筋 割る トレーニング"),
    advice: "腹筋の基本がわかりやすく学べます。間違ったフォームで首や腰を痛めないためのポイントが参考になります!",
  },
  {
    id: "metron-abs-3min",
    title: "【3分】腹筋を割るトレーニング",
    youtuber: "メトロンブログ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("メトロンブログ 3分 腹筋 割る"),
    advice: "たった3分で腹筋を追い込めるメニュー。毎日続けやすい短時間メニューです!",
  },
  {
    id: "ufit-abs-home",
    title: "自宅でできる腹筋トレ8種",
    youtuber: "uFit 林ケイスケ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("林ケイスケ uFit 腹筋 自宅 トレーニング"),
    advice: "クランチからプランクまでバリエーション豊富。動画を見ながら一緒にやれるのが便利です!",
  },
  {
    id: "sho-abs",
    title: "腹筋トレーニングの科学的アプローチ",
    youtuber: "Sho Fitness",
    level: "中級者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("Sho Fitness 腹筋 トレーニング 科学的"),
    advice: "腹筋を効率的に鍛えるための科学的な解説。上部・下部・腹斜筋それぞれの鍛え方が学べます。",
  },
  {
    id: "katochan-plank",
    title: "プランクの正しいやり方と応用",
    youtuber: "katochan33",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("katochan33 プランク 正しいやり方"),
    advice: "体幹を鍛える定番種目プランク。正しい姿勢のポイントと、慣れてきた人向けの応用バリエーションが紹介されています。",
  },
  {
    id: "metron-lower-abs",
    title: "下腹部を凹ませるトレーニング",
    youtuber: "メトロンブログ",
    level: "中級者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("メトロンブログ 下腹部 トレーニング"),
    advice: "落ちにくい下腹部に特化したメニュー。レッグレイズ系の種目で下腹部をしっかり追い込めます!",
  },
  {
    id: "kinniku-sideplank",
    title: "腹斜筋を鍛えてくびれを作る",
    youtuber: "なかやまきんに君",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("なかやまきんに君 腹斜筋 くびれ"),
    advice: "お腹の横を鍛えてくびれを作るメニュー。サイドプランクやツイスト系の種目がわかりやすく解説されています。",
  },
];
