import { Video, youtubeSearch } from "./videoTypes";

export const armVideos: Video[] = [
  {
    id: "kinniku-arm",
    title: "太い腕を作る筋トレメニュー",
    youtuber: "なかやまきんに君",
    level: "初心者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("なかやまきんに君 腕 筋トレ 太い"),
    advice: "二頭筋と三頭筋をバランスよく鍛えるメニュー。初心者にもわかりやすい解説が魅力です!",
  },
  {
    id: "sho-curl",
    title: "アームカールの正しいやり方",
    youtuber: "Sho Fitness",
    level: "初心者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("Sho Fitness アームカール 正しいやり方"),
    advice: "力こぶを大きくする基本種目。反動を使わず丁寧に効かせるコツが学べます。",
  },
  {
    id: "katochan-triceps",
    title: "三頭筋を鍛えるトレーニング",
    youtuber: "katochan33",
    level: "初心者",
    equipment: "マシン",
    youtubeUrl: youtubeSearch("katochan33 三頭筋 トレーニング"),
    advice: "腕の太さの2/3は三頭筋。太い腕を作るなら三頭筋トレは必須です。ケーブルプレスダウンの解説が特に参考になります。",
  },
  {
    id: "metron-arm",
    title: "腕を太くする自重トレーニング",
    youtuber: "メトロンブログ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("メトロンブログ 腕 太くする 自重"),
    advice: "ダンベルがなくても腕は鍛えられる!ナロープッシュアップなど自重で三頭筋に効く種目が学べます。",
  },
  {
    id: "ufit-arm-home",
    title: "自宅でできる腕トレ5分メニュー",
    youtuber: "uFit 林ケイスケ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("林ケイスケ uFit 腕 トレーニング 自宅"),
    advice: "5分で終わる腕トレメニュー。毎日のルーティンに組み込みやすい内容です!",
  },
  {
    id: "sho-hammer-curl",
    title: "ハンマーカールで前腕も鍛える",
    youtuber: "Sho Fitness",
    level: "中級者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("Sho Fitness ハンマーカール 前腕"),
    advice: "通常のカールと角度を変えるだけで前腕と上腕筋にも効きます。腕全体のバランスを整えたい方におすすめ。",
  },
  {
    id: "yokokawa-arm",
    title: "腕トレーニングルーティン",
    youtuber: "横川尚隆",
    level: "中級者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("横川尚隆 腕 トレーニング ルーティン"),
    advice: "ボディビル王者の腕トレは追い込み方が参考になります。二頭・三頭のスーパーセットの組み方が学べます。",
  },
];
