import { Video, youtubeSearch } from "./videoTypes";

export const backVideos: Video[] = [
  {
    id: "sho-deadlift",
    title: "デッドリフトの正しいフォーム徹底解説",
    youtuber: "Sho Fitness",
    level: "初心者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("Sho Fitness デッドリフト 正しいフォーム"),
    advice: "背中トレの王道デッドリフト。腰を痛めないフォームが丁寧に解説されています。初心者はまずこの動画で基本を学びましょう。",
  },
  {
    id: "sho-chinup",
    title: "懸垂(チンニング)の正しいやり方",
    youtuber: "Sho Fitness",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("Sho Fitness 懸垂 チンニング 正しいやり方"),
    advice: "広背筋を鍛える最強の自重種目。できない人向けのステップアップ方法も紹介されていて実践的です。",
  },
  {
    id: "kinniku-back",
    title: "背中を鍛える自重トレーニング",
    youtuber: "なかやまきんに君",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("なかやまきんに君 背中 自重トレーニング"),
    advice: "器具なしでできる背中トレ。初心者でもわかりやすい解説で、自宅トレに最適です!",
  },
  {
    id: "katochan-lat",
    title: "ラットプルダウンの効かせ方",
    youtuber: "katochan33",
    level: "初心者",
    equipment: "マシン",
    youtubeUrl: youtubeSearch("katochan33 ラットプルダウン 効かせ方"),
    advice: "ジム初心者がまず覚えるべきマシン種目。肩甲骨の動かし方を意識するだけで効果が全然変わります。",
  },
  {
    id: "sho-barbell-row",
    title: "ベントオーバーロウの正しいフォーム",
    youtuber: "Sho Fitness",
    level: "中級者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("Sho Fitness ベントオーバーロウ フォーム"),
    advice: "背中の厚みをつけるならこの種目。前傾角度と引く位置で効く部位が変わるので、動画でしっかり確認しましょう。",
  },
  {
    id: "ufit-back-home",
    title: "自宅でできる背中トレ6種",
    youtuber: "uFit 林ケイスケ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("林ケイスケ uFit 背中 自宅 トレーニング"),
    advice: "タオルを使った背中トレなど工夫が満載。ジムに行けない日の背中トレとして活用できます!",
  },
  {
    id: "yokokawa-back",
    title: "背中トレーニングルーティン",
    youtuber: "横川尚隆",
    level: "中級者",
    equipment: "マシン",
    youtubeUrl: youtubeSearch("横川尚隆 背中 トレーニング ルーティン"),
    advice: "日本王者の背中トレを見て学べます。マインドマッスルコネクションの大切さがよくわかる動画です。",
  },
  {
    id: "metron-back",
    title: "背中を広くする自重トレーニング",
    youtuber: "メトロンブログ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("メトロンブログ 背中 広くする 自重"),
    advice: "逆三角形の体を作るための自重メニュー。音楽に合わせて楽しくトレーニングできます!",
  },
];
