import { Video, youtubeSearch } from "./videoTypes";

export const chestVideos: Video[] = [
  {
    id: "sho-bench-beginner",
    title: "【初心者】正しいベンチプレス講座",
    youtuber: "Sho Fitness",
    level: "初心者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("Sho Fitness 初心者 正しいベンチプレス講座"),
    advice: "科学的根拠に基づいた解説で、フォームの基礎から重量設定まで網羅されています。初心者は必ず見てほしい動画です!",
  },
  {
    id: "goldsgym-bench",
    title: "ゴールドジム公式・ベンチプレス解説",
    youtuber: "ゴールドジム",
    level: "初心者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("ゴールドジム ベンチプレス 解説"),
    advice: "プロボディビルダーによる解説で、安全面の注意点もしっかり学べます。特に肩を痛めないためのポイントが参考になります。",
  },
  {
    id: "sho-dumbbell-press",
    title: "ダンベルプレスの正しいやり方",
    youtuber: "Sho Fitness",
    level: "初心者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("Sho Fitness ダンベルプレス 正しいやり方"),
    advice: "肩甲骨の使い方が本当にわかりやすいです。可動域を広く取れるダンベルプレスは、ベンチプレスと組み合わせると効果的!",
  },
  {
    id: "yokokawa-dumbbell-fly",
    title: "【ダンベルフライ】日本王者のガチトレ",
    youtuber: "横川尚隆",
    level: "中級者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("横川尚隆 ダンベルフライ"),
    advice: "トップビルダーの実践的テクニックが学べます。可動域の取り方と、胸にしっかり効かせる感覚を掴みましょう。",
  },
  {
    id: "kinniku-pushup",
    title: "なかやまきんに君の正しい腕立て伏せ",
    youtuber: "なかやまきんに君",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("なかやまきんに君 正しい腕立て伏せ"),
    advice: "超わかりやすい!よくある間違いを丁寧に指摘してくれます。自重トレでも正しいフォームなら十分効きます。",
  },
  {
    id: "ufit-chest-8",
    title: "胸板を厚くする自重トレ8種【3分】",
    youtuber: "uFit 林ケイスケ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("林ケイスケ uFit 胸 自重トレ"),
    advice: "バリエーション豊富で飽きません。動画を見ながら一緒にやれるので、自宅トレに最適です!",
  },
  {
    id: "sho-incline",
    title: "インクラインベンチプレスの角度設定",
    youtuber: "Sho Fitness",
    level: "中級者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("Sho Fitness インクラインベンチプレス 角度"),
    advice: "大胸筋上部を狙うなら30-45度の角度設定が重要。フラットベンチプレスと組み合わせてバランス良く鍛えましょう。",
  },
  {
    id: "metron-3min",
    title: "【3分間】短時間胸トレ",
    youtuber: "メトロンブログ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("メトロンブログ 3分 胸トレ"),
    advice: "忙しい日でもこれならできる!短時間でも追い込めます。時間がない日はこういう短時間トレーニングが最適です。",
  },
  {
    id: "jin-bench-100kg",
    title: "ぷろたんとベンチプレス100kg挑戦",
    youtuber: "JIN",
    level: "中級者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("JIN ぷろたん ベンチプレス 100kg"),
    advice: "重量を伸ばすコツが学べます。フィジーク選手のJINさんの解説は実践的で参考になります!",
  },
];
