import { Video, youtubeSearch } from "./videoTypes";

export const legVideos: Video[] = [
  {
    id: "sho-squat",
    title: "スクワットの正しいフォーム徹底解説",
    youtuber: "Sho Fitness",
    level: "初心者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("Sho Fitness スクワット 正しいフォーム"),
    advice: "キングオブトレーニング・スクワット。膝の向きや深さなど、怪我を防ぐポイントが丁寧に解説されています。",
  },
  {
    id: "kinniku-squat",
    title: "正しいスクワットのやり方",
    youtuber: "なかやまきんに君",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("なかやまきんに君 正しい スクワット やり方"),
    advice: "自重スクワットの基本をわかりやすく解説。膝が痛くならないフォームのコツが学べます!",
  },
  {
    id: "ufit-leg-home",
    title: "自宅でできる脚トレメニュー",
    youtuber: "uFit 林ケイスケ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("林ケイスケ uFit 脚 トレーニング 自宅"),
    advice: "器具なしの脚トレメニュー。ランジやブルガリアンスクワットなどバリエーション豊富です!",
  },
  {
    id: "katochan-legpress",
    title: "レッグプレスの正しい使い方",
    youtuber: "katochan33",
    level: "初心者",
    equipment: "マシン",
    youtubeUrl: youtubeSearch("katochan33 レッグプレス 正しい 使い方"),
    advice: "ジム初心者におすすめのマシン種目。足の位置で効く部位が変わるので、動画で確認しましょう。",
  },
  {
    id: "sho-romanian-dl",
    title: "ルーマニアンデッドリフトのフォーム",
    youtuber: "Sho Fitness",
    level: "中級者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("Sho Fitness ルーマニアンデッドリフト フォーム"),
    advice: "ハムストリングスとお尻を集中的に鍛える種目。膝の曲げ具合と股関節のヒンジがポイントです。",
  },
  {
    id: "yokokawa-leg",
    title: "脚トレーニングルーティン",
    youtuber: "横川尚隆",
    level: "中級者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("横川尚隆 脚 トレーニング ルーティン"),
    advice: "日本王者の脚トレは追い込み方がすごい。高重量スクワットのフォームが参考になります。",
  },
  {
    id: "metron-leg",
    title: "下半身を鍛える自重トレーニング",
    youtuber: "メトロンブログ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("メトロンブログ 下半身 脚 自重トレーニング"),
    advice: "音楽に合わせた脚トレメニュー。ジャンプスクワットなど有酸素要素もあり、脂肪燃焼にも効果的!",
  },
  {
    id: "katochan-hip",
    title: "ヒップスラストでお尻を鍛える",
    youtuber: "katochan33",
    level: "中級者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("katochan33 ヒップスラスト お尻"),
    advice: "お尻を集中的に鍛えるヒップスラスト。ヒップアップしたい方は必見の種目です。",
  },
];
