import { Video, youtubeSearch } from "./videoTypes";

export const shoulderVideos: Video[] = [
  {
    id: "sho-overhead-press",
    title: "オーバーヘッドプレスの正しいやり方",
    youtuber: "Sho Fitness",
    level: "初心者",
    equipment: "バーベル",
    youtubeUrl: youtubeSearch("Sho Fitness オーバーヘッドプレス 正しいやり方"),
    advice: "肩を大きくするための基本種目。正しいフォームで行えば肩の怪我を防げます。まずはこの動画から始めましょう。",
  },
  {
    id: "kinniku-shoulder",
    title: "肩を大きくするトレーニング3選",
    youtuber: "なかやまきんに君",
    level: "初心者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("なかやまきんに君 肩 トレーニング"),
    advice: "初心者でもわかりやすい肩トレの基本。サイドレイズのフォームが特に参考になります!",
  },
  {
    id: "sho-side-raise",
    title: "サイドレイズの正しいフォーム",
    youtuber: "Sho Fitness",
    level: "初心者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("Sho Fitness サイドレイズ 正しいフォーム"),
    advice: "肩の横を鍛えるサイドレイズ。軽い重量でも正しいフォームなら十分効きます。僧帽筋に逃げないコツが学べます。",
  },
  {
    id: "katochan-rear",
    title: "リアレイズで肩の後ろを鍛える",
    youtuber: "katochan33",
    level: "中級者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("katochan33 リアレイズ 肩 後ろ"),
    advice: "見落としがちな肩の後部。丸い肩を作るにはリアレイズが欠かせません。フォームのコツが詳しく解説されています。",
  },
  {
    id: "ufit-shoulder-home",
    title: "自宅でできる肩トレメニュー",
    youtuber: "uFit 林ケイスケ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("林ケイスケ uFit 肩 自宅 トレーニング"),
    advice: "器具なしで肩を鍛えるメニュー。パイクプッシュアップなど自重でも肩に効く種目が学べます!",
  },
  {
    id: "yokokawa-shoulder",
    title: "三角筋を大きくするトレーニング",
    youtuber: "横川尚隆",
    level: "中級者",
    equipment: "ダンベル",
    youtubeUrl: youtubeSearch("横川尚隆 三角筋 トレーニング"),
    advice: "ボディビル王者の肩トレを間近で見られます。高重量と丁寧なフォームの両立が勉強になります。",
  },
  {
    id: "metron-shoulder",
    title: "メロン肩を作る自重トレーニング",
    youtuber: "メトロンブログ",
    level: "初心者",
    equipment: "自重",
    youtubeUrl: youtubeSearch("メトロンブログ 肩 自重 トレーニング"),
    advice: "丸い肩を目指す自重メニュー。短時間で追い込めるので忙しい日にもおすすめです!",
  },
];
